### ISSUE TITLE
Back to JSON

### ISSUE THREAD

**Issue by GegeFR** [lukas-krecan/json2xml#13]
Hello,

I love using you library to parse complicated JSON documents using XPath (seems bullet-proof compared to JsonPath implementations).

I'd like to use XPath to selected nodes and edit them. Is there a way to go back from the XML to a json document ?

**Comment by lukas-krecan** [comment]
Hi, I am not aware of anything like that, but I think that you can easily implement it for example by connecting SAX parser and Jackson generator http://tutorials.jenkov.com/java-json/jackson-jsongenerator.html
