### ISSUE TITLE
help!!!

### ISSUE THREAD

**Issue by cczuwangkun** [lukas-krecan/json2xml#31]
this is my xml file:
<ceb:CEB303Message xmlns:ceb="http://www.chinaport.gov.cn/ceb" guid="A8B20EBF-7026-4F93-922F-6DA7" version="1.0">
    <ceb:BaseTransfer>
        <ceb:copCode>320796397L</ceb:copCode>
        <ceb:copName>aaa</ceb:copName>
        <ceb:dxpMode>DXP</ceb:dxpMode>
        <ceb:dxpId>bbb</ceb:dxpId>
        <ceb:note></ceb:note>
    </ceb:BaseTransfer>
</ceb:CEB303Message>

i have two questions:
1.  xmlns:ceb="http://www.chinaport.gov.cn/ceb" guid="A8B20EBF-7026-4F93-922F-6DA7"   how to generate this
2. <ceb:note></ceb:note>  I don't want to abbreviate it as <ceb:note/>

I would like to get the code you wrote if possible！！！thanks！！！！

**Comment by javadev** [comment]
You may prepare a json to generate an xml.

```json
{
  "ceb:CEB303Message": {
    "-xmlns:ceb": "http://www.chinaport.gov.cn/ceb",
    "-guid": "A8B20EBF-7026-4F93-922F-6DA7",
    "-version": "1.0",
    "ceb:BaseTransfer": {
      "ceb:copCode": "320796397L",
      "ceb:copName": "aaa",
      "ceb:dxpMode": "DXP",
      "ceb:dxpId": "bbb",
      "ceb:note": {
      }
    }
  },
  "#omit-xml-declaration": "yes"
}
```
<ceb:CEB303Message xmlns:ceb="http://www.chinaport.gov.cn/ceb" guid="A8B20EBF-7026-4F93-922F-6DA7" version="1.0">
<ceb:BaseTransfer>
<ceb:copCode>320796397L</ceb:copCode>
<ceb:copName>aaa</ceb:copName>
<ceb:dxpMode>DXP</ceb:dxpMode>
<ceb:dxpId>bbb</ceb:dxpId>
<ceb:note></ceb:note>
</ceb:BaseTransfer>
</ceb:CEB303Message>
```xml
