### ISSUE TITLE
JSON key names that are not legal XML element names

### ISSUE THREAD

**Issue by dwcramer** [lukas-krecan/json2xml#9]
Given the input JSON:

```
{
   "^.{0,256}$": "foo"
}
```

How would this be converted to XML? It appears from the docs that this plugin would attempt to create the XML &lt;^.{0,256}$>foo&lt;/^.{0,256}$>, but that would not be well-formed xml since ^.{0,256}$ isn't a legal element name. 

I would suggest an xml format like &lt;key name="^.{0,256}$">foo&lt;/key> to avoid this problem. 

Addendum: I just saw the name converter section of the readme. That seems like a strange way to go about it since you lose data from the input JSON when putting the JSON names into attributes solves the same problem.

**Comment by javadev** [comment]
@dwcramer

[underscore-java](https://github.com/javadev/underscore-java) can convert json to xml.

```json
{
  "^.{0,256}$": "foo"
}
```

will be converted to:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<__LY__.__PM__0__FQ__256__PU____EQ__>foo</__LY__.__PM__0__FQ__256__PU____EQ__>
```
